#!/usr/bin/nft -f

flush ruleset

table inet tb321fu_filter {
    chain input {
        type filter hook input priority filter; policy drop;

        ct state invalid drop
        ct state established,related accept
        iifname "lo" accept

        ip protocol icmp accept
        meta l4proto ipv6-icmp accept

        udp sport 67 udp dport 68 accept
        udp sport 547 udp dport 546 accept

        tcp dport 22 ip saddr {
            10.0.0.0/8,
            172.16.0.0/12,
            192.168.0.0/16,
            169.254.0.0/16
        } ct state new limit rate 20/minute burst 10 packets accept

        tcp dport 22 ip6 saddr {
            fc00::/7,
            fe80::/10
        } ct state new limit rate 20/minute burst 10 packets accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
