wireplumber.components = [
  {
    name = y700/headset-cleanup.lua, type = script/lua
    provides = hooks.device.routes.y700-headset-cleanup
  }
]

wireplumber.components.rules = [
  {
    matches = [
      { provides = policy.device.routes }
    ]
    actions = {
      merge = {
        wants = [ hooks.device.routes.y700-headset-cleanup ]
      }
    }
  }
]
